### PR TITLE
Better error handling

### LINKED ISSUE #7: Better error handling
In order to speed up development, we have been using `color-eyre` to conveniently handle errors in `rpmspec-rs`. This is of course poor practice and should be mitigated.

- [ ] Port all errors to `thiserror`
- [ ] Merge, separate and organize different errors as accordingly (in different categories)
- [ ] Absolutely phase out the use of `color-eyre`
- [ ] Include "span" and better position support for `Consumer`
- [ ] Use [ariadne](https://github.com/zesterer/ariadne/) for traceback-like error messages

### PR DESCRIPTION
**Pull request by korewaChino**
Closes #7

### CODE REVIEW

**Comment by dralley** [comment]
Personally, I prefer rebases over merges, especially before a PR is merged

**Comment by madonuko** [comment]
There was a merge conflict so I used the GitHub merge conflict interface to solve the conflict, which unfortunately forces merges. I could've used the cli but it's pretty annoying when it's an outside repository I have no direct git access to.

**Comment by korewaChino** [comment]
I apologize about that, should've given @madonuko access to my fork.

**Comment by madonuko** [comment]
Superseded by #13.

**Pull request merged**
